name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@v4
        with:
          use-flakehub: false

      - name: Build
        run: nix build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/catppuccin-discord/
          destination_dir: dist
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
